# Generated by Django 4.2.7 on 2023-11-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_alter_employees_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='firstname',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employees',
            name='lastname',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employees',
            name='midname',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='profession',
            field=models.TextField(max_length=20),
        ),
    ]
