# Generated by Django 4.2.7 on 2023-11-19 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_alter_employees_firstname_alter_employees_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professions', to='baseapp.professions'),
        ),
    ]
