# Generated by Django 4.2.7 on 2023-11-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_alter_employees_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='firstname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employees',
            name='lastname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employees',
            name='midname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
